server:
    port: 8080
spring:
    rabbitmq:
        host: 47.100.29.15
        port: 5672
        username: admin
        password: 123456
    mail:
        host: smtp.qq.com
        username: 532968876@qq.com
        password: pkntcevtxemfcaeb
        properties:
          mail:
             smtp:
               auth: true
               timeout: 25000
               starttls:
                 enable: true
                 required: true
               socketFactory:
                 port: 465
                 class: javax.net.ssl.SSLSocketFactory
                 fallback: false
          default-encoding: UTF-8
          port: 465